# Jupyter, numpy et scipy

## Installation de Jupyter notebook :
* Installation de la bibliothèque : pip install jupyter
* Installer l'extension Jupyter dans VS Code : menu extension ou (CTRL+Shift+X)
* Documentation : https://jupyter.org/
* Tester avec un exemple

In [2]:
print("hello world")

hello world


## Installation de numpy :
* Installation de la bibliothèque : pip install numpy
* Ajouter numpy à un projet : import numpy as np
* Documentation : https://numpy.org/ 
* Tester l'import

Vérifier l'installation 

In [3]:
import numpy as np
import pandas as pd

### Création de matrices avec numpy
* matrice simple

In [4]:
M1 = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
M1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**answer**
```py
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
```


* Modifier les dimensions d'une matrice

In [26]:
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**answer**

```py
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
```

### Accéder aux données
* Accéder à un élément en particulier
* Accéder à une colonne
* Accéder à une ligne

array([0, 1, 2, 3, 4])

### Informations sur la matrice
* Dimensions de la matrice
* Nombre d'éléments dans la matrice
* Type des éléments
* Nombre d'axes

In [32]:

np.info(M1)
M1.shape
M1.size
M1.dtype
M1.ndim


class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7fb278e24d30
byteorder:  little
byteswap:  False
type: int64


2

## Installation de scipy :
* Installation de la bibliothèque : pip install scipy
* Ajouter scipy à un projet : import scipy
* Documentation : https://scipy.org/
* Tester l'import
* Nous nous sevirons de scipy uniquement pour représenter des diagrammes de regroupement hiérarchique